//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class BoardView:public drogon::DrTemplate<BoardView>
{
public:
	BoardView(){};
	virtual ~BoardView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
