//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "BoardView.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string BoardView::genText(const DrTemplateData& BoardView_view_data)
{
	drogon::OStringStream BoardView_tmp_stream;
	std::string layoutName{""};
 for(int i=0; i<7; i++) {
	BoardView_tmp_stream << "<div class=\"column\" id=\"col{%i}\">\n";
	BoardView_tmp_stream << "	";
 for(int j=0; j<6; j++) {
	BoardView_tmp_stream << "		<div class=\"box\" id=\"cell{%i}{%j}\"></div>\n";
	BoardView_tmp_stream << "	";
}
	BoardView_tmp_stream << "</div>\n";
}
if(layoutName.empty())
{
std::string ret{std::move(BoardView_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = BoardView_view_data;
auto str = std::move(BoardView_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
